application: tryhy
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: index.html
  upload: index\.html

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: .*
  script: main.__hymain__.app
